version: 2.1

executors:
  foo:
    docker:
      - image: alpine:3.18
    resource_class: medium

  bar:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

jobs:
  test:
    executor: foo
    steps:
      - run:
          name: Install git
          command: apk add git
      - run:
          name: Git version
          command: git version
      - run:
          name: Custom checkout
          command: |
            git clone --filter=blob:none --no-checkout https://github.com/DomParfitt/scratch-public .
            git fetch

workflows:
  default:
    jobs:
      - test
