version: 2.1

executors:
  foo:
    docker:
      - image: cimg/base:2021.04
    resource_class: medium

  bar:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

jobs:
  test:
    executor: bar
    steps:
      - run:
          name: Custom checkout
          command: git clone --filter=blob:none --no-checkout https://github.com/DomParfitt/scratch .

workflows:
  default:
    jobs:
      - test
