version: 2.1

executors:
  foo:
    docker:
      - image: cimg/node:20.10
    resource_class: medium

  bar:
    machine:
      image: ubuntu-2004:current
    resource_class: medium

jobs:
  test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - run:
          name: Git version
          command: git version
      - checkout

workflows:
  default:
    jobs:
      - test:
          matrix:
            parameters:
              executor:
                - foo
                - bar
